import streamlit as st
import passwordprotect
import sqlcust
import mail
def sign_up(data):
    st.markdown(
    """
    <style>
    .reportview-container {
        background: url("https://www.colorhexa.com/d3d3d3.png")
    }
   
    </style>
    """,
    unsafe_allow_html=True
)

    st.subheader("welcome to ADDIS TRADES INC. \n THE SAFEST STOCK BROKERAGE SYSTEM \n CREATE ACCOUNT")
    col1, col2 = st.beta_columns(2)
    with col1:
        new_name = st.text_input('full name')
        new_user=st.text_input('username')
        new_pass=passwordprotect.secure(st.text_input('password',type='password'))
        bank_details=(st.text_input('15 digit bank account number',max_chars=15))
        new_pin = (st.text_input('IPIN',type='password'))
        new_mail =  st.text_input('email')
    st.subheader('')
    my_expan1 = st.beta_expander('ABOUT STOCK AND TRADE')
    with my_expan1:
        st.write("AN INTRODUCTION TO STOCK MARKET BY Ted-Ed")
        st.video('https://www.youtube.com/watch?v=p7HKvqRI_Bo')
    my_expan = st.beta_expander('TERMS AND CONDITIONS')
    with my_expan:
        st.write('1.    Stock market and trading is soley done on my choice and all information given is true to my knowledge')
        st.write('2.    I accept that Addis Trades Incorporated is just the mediator of all the purchases of stock and are in no way pressurising me.')
        st.write('3.    The members of Addis Trades Incorporated are in no way manipulating me and all profit and loss are all because of me.')
        st.write('INTELLECTUAL PROPERTY RIGHTS')
        st.write("1.	The application offers financial and investment information created by Addis Trades Inc. as well as other information collected from third-party applications. In so far as the materials and information created by Addis Trades Inc. is concerned, such materials and information are created using Addis Trades Inc.’s proprietary tools and methods and belong to Addis Trades Inc. and are thus protected by intellectual property laws of United States and other jurisdictions \n 2.	The references to trademarks, trade names, business names and other proprietary information of third party applications do not amount to an endorsement or recommendation by Addis Trades Inc.. All materials, information and content that may be referenced on the Application and belonging to third parties constitute the intellectual property of such third party and Addis Trades Inc. claims no ownership rights in respect thereof. Addis Trades Inc. is not responsible for the content of or any damage that may result from the User’s access to or reliance on third-party applications. If the User links to third-party applications, he/she does so at his/her own risk.\n3.	By using this Application, the User is granted a limited, non-exclusive, non-transferable and revocable right to use the content and materials on the Application in connection with his/her personal and non-commercial use of the Application. The Users shall not alter, copy, reproduce, transmit, distribute, or create derivative works of such materials or information without express written authorization from Addis Trades Inc. or the third party as the case may be.\n4.	The Users acknowledges that his/her use of the content on this Application is for personal and non-commercial use only and any unauthorized use of the materials and information may violate copyright, trademark, and/or other laws.\n5.	Any permitted copies of the content and materials on the Application or portions thereof must retain all copyright notices and other notices thereon.\n6.	Nothing on the Application shall be construed as conferring any license in respect of the contents and information thereon except as otherwise provided.\n7.	Addis Trades Inc. may revoke any rights granted to the Users with respect to use of the Application at any time.\n8.	By posting, uploading, storing, or transmitting any content on the Application, the User hereby grants to Addis Trades Inc. a perpetual, worldwide, non-exclusive, royalty-free, assignable right and license to use, modify, copy, display, perform, create derivative works from, distribute, have distributed, transmit and assign such content in any form, in all media now known or hereinafter created, anywhere in the world.\n9.	Addis Trades Inc. does not have the ability to control the nature of the content generated by other Users and offered through the Application. Users are solely responsible for their interactions with other Users of the Application and for all content posted by him/her. It is expressly made clear that Addis Trades Inc. is not liable for any damage or harm resulting from any posts by or interactions between Users inter-se. Users grant to Addis Trades Inc. the right and license to publish, exhibit, use and transmit all content posted by them on the Application for its own purposes or to third parties in connection with the provision of Services.")
        
        
        st.write("THE AGREEMENT ")
        st.write(" 1 These Terms and Conditions form part of the agreement between you, the client ('You', 'Your(s) or 'yourself'), and Addis Trades Inc Limited ('Addis Trades Inc', 'we', 'us', 'ourselves' or 'our(s)'). These govern the services offered by us our relationship with you and all transactions that you enter into with us (or any Authorised Third Party using your name, account number and/or password).")
        st.write("2 We are authorised and regulated in the United States by the Financial Conduct Authority (FCA), whose address is 12 Endeavour Square, New York E20 1JN. Our FCA registration number is 679941. For certain services we may be regulated by other professional or governmental bodies. If such is the case these separate terms are set out in their relevant sections (Supplemental Terms).")
        st.write("3 All the services we offer under this Agreement are regulated by the FCA and are covered by the FCA Rules and regulations.")
        st.write("4 These Terms and Conditions together with the Risk Disclosure Notice, your Application Form, the Order Execution Policy, the Conflict of Interest Policy and any supplemental terms and conditions or policies issued by us, are known as the 'Agreement'. Before you invest you should read these documents and ensure that you understand them.")
        st.write("5 You should read these terms in their entirety. If there is any part of these terms that you do not understand you should contact us immediately. Unless we agree, in writing, to amend any part of this Agreement it will form the basis of all contracts that you enter into with us. This Agreement and all subsequent amendments that you agree to are legally binding and enforceable.")
        st.write("6 The meanings of certain financial and legal wordings are set out in the 'Glossary' at the end of this document.")
        st.write("7 We act as an execution-only broker and will provide all stockbroking and investment services. We will also hold and administer your money and Assets as custodian. We may delegate certain obligations under this Agreement to any associated company third parties.")
        st.write("8 You may contact us via email or verbally by telephone. All such communications should be in English. We may converse with/write to, you in languages other than English but in the event of any misunderstanding or error the English version of this agreement will prevail. The English version of this Agreement is binding and takes precedence over any other translation. All communications with you are made on a best endeavours basis and, unless agreed in writing by a Director of Addis Trades Inc, do not alter this Agreement.")
        st.write("9 You agree that we will be entitled to take any action as we consider necessary, in our absolute discretion, to ensure compliance with Applicable Laws. You agree to comply with all Applicable Laws and also to abide by any local laws to which you may be subject. You are reminded that this especially applies to all forms of market abuse (e.g.:- market manipulation or insider trading) and corporate governance (e.g.:- director trading).")
        st.write("10 Trading via our stockbroking platform is not suitable for everyone. A full explanation of the risks associated with using our services is set out in the Risk Disclosure Notice and you should ensure you fully understand such risks before entering into this Agreement with us.")
        st.write("11 You authorise us to telephone or otherwise contact you at any time whatsoever in order to discuss your account or to communicate other services offered by us.")
        st.write("12 We will not offer any advice on the suitability of your entering into this Agreement. It is entirely your personal choice as to whether you should use our services. We strongly recommend that you take professional advice before entering into this agreement.")
        st.write("13 You agree that we may share commissions and charges with our Trading Partners or other third parties, and receive or pay remuneration from or to the same in respect of trades entered into by you with us. Such commissions and charges will only be paid where we are satisfied that such payments do not impair our obligation to act in your best interests and meet our regulatory obligations.")
        st.write("14 You agree that where a situation arises that is not covered by this agreement then you and we will be bound by general industry norms and where possible or relevant with reference to the Terms and Conditions of our competitor companies.")
        st.write("15 Nothing in this Agreement will over rule our duty or liability to you under the Financial Services and Markets Act 2000 (as amended) or the FCA Rules and if there is any conflict between this Agreement and the FCA Rules, the FCA Rules will prevail.")
        st.write("16 You acknowledge that the Product Information Sheets that apply to any Asset in which you have an interest or wish to trade will be displayed online on our website. Such information is provided on a best endeavours basis and may be updated from time to time. We shall not be liable to you for any such incorrect information.")
        st.write("17 All calls to our telephone lines are recorded and you hereby agree to this recording. All recordings of telephone conversations are our exclusive property and may be used as evidence in any dispute.")
        st.write("18 We may assign, in whole or in part, the rights and obligations of this Agreement to a third-party provided that any assignee agrees to abide by the Terms of this Agreement and subject to the approval of the FCA. Such assignment will come into effect 10 business days following the day you are deemed to have received notice of the assignment. If we do assign our rights and obligations under this Agreement, we will only do so to a third-party who is competent to carry out the functions and responsibilities and who will provide the same standard of service that we do.")
        st.write("19 Our rights and obligations under this Agreement are solely to you. You may not assign either the benefit or burden of any part of this Agreement to any third-party without our prior written consent.")
        
        
        
    
    clicked = st.checkbox('I agree to all terms and conditions')
    if clicked:
        if st.button("sign up"):
           i = 0
           while i<len(data):
               if new_user == data[i][0]:
                   st.info("username taken")
                   break
               i = i+1
           else:
               sqlcust.add_data(new_user,new_name,new_pass,new_pin,bank_details,new_mail)
               st.success("valid account created")
               st.info("go to login")
               mail.sub(new_mail)
               